### ISSUE TITLE
command line arguments for compile are missing

### ISSUE THREAD

**Issue by agruzman** [agruzman/yamlp#3]
Minimal args are:
-compile
-results [optional]
-model_compile [optional]

**Comment by operlmut** [comment]
compile <hdl tool> ? or  just compile ?

**Comment by agruzman** [comment]
think about cmd line object

**Comment by operlmut** [comment]
I can think on something :-)

still missing:
1) Master generation.
2) exec shell script that call the Master.
3) cmd line parser.
4) **put\get_libs**
5) unit-test
6) hooks
7) post process

**Comment by agruzman** [comment]
yalla, come with proposal of command line object

**Comment by operlmut** [comment]
There are only 2 options to implement with argsparse a three state type. that if you didn't specified it it get 'None' value and get it's value from yaml file, else get 'True' or 'False' from the cmd line.
attaching the code, you can see the '-nb' and '-nonb' had to explicitly defined as a mutually_exclusive_group.
and for '-fsdb' it use a HomeMade three_state_type function and Once class to verify it appears only once, the usage is also different to unset "-fsdb 0 | -fsdb false".

Please let me know what you prefer
[argsparser_debug.zip](https://github.com/agruzman/yamlp/files/469639/argsparser_debug.zip)

**Comment by agruzman** [comment]
```
no, this is not good enough. It must get connected to the built_in configuration file. Where all the command line options are categorized and explained.
Please look at my last commit and see there file called :  MakeConfig/built_in_configuration.yaml
....

COMMAND_LINE_OPTS:
  **common**:
    target :
      results :
        type: string
        help: "This is where tests results are going to"
        default : "**<REF:** COMMAND_LINE_OPTS/target/model_results>" ## REF: means valid YAML input path
      model_results:
        type: string
        help : "This is where the model gets compiled to"
        default : "./"
      tmp_space:
        type: string
        help : "This is where the temp data is going"
        default : "/tmp"

```

**Comment by operlmut** [comment]
you have several issues in your latest built_in_configuration.yaml update:
**1)** subparsers are not supporting shortcut, so compile|comp currently isn't relevant.
**2)** on the new runtest|exec action you put the nested *DEFAULT_MODEL on second level i.e. under test::model... is it really necessary? why can't we separate the test and the model to 2 different options like the rest? 
**3)** you put the elab|elaborate help in the same level as the rest of the switches which required a special treatment. you should create a new level for the switches like:
elab|elaborate:
  help: "i'm very helpfule"
  **options**:
    opts:
      <<: *DEFAULT_COMP_EL_VERDI_OPTS
    clean: 
      <<: *DEFAULT_CLEANUP
**4**) need to be consistent if the option name without '-' the shortcut shouldn't be also.

**Comment by agruzman** [comment]
Most of the above is fixed and agreed.
wemake rundtest -test <testdir> -sim [-other test parameters] [common parameters such as compile dir and results dir]

**Comment by agruzman** [comment]
The issue has been closed
